// Mocks generated by Mockito 5.0.14 from annotations
// in submission_final/test/data/restaurant_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:submission_final/data/api/api_service.dart' as _i4;
import 'package:submission_final/data/model/restaurant.dart' as _i2;
import 'package:submission_final/data/model/review.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRestaurantList_0 extends _i1.Fake implements _i2.RestaurantList {}

class _FakeRestaurantDetail_1 extends _i1.Fake implements _i2.RestaurantDetail {
}

class _FakeRestaurantSearch_2 extends _i1.Fake implements _i2.RestaurantSearch {
}

class _FakeResponseReview_3 extends _i1.Fake implements _i3.ResponseReview {}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RestaurantList> restaurantList() =>
      (super.noSuchMethod(Invocation.method(#restaurantList, []),
              returnValue:
                  Future<_i2.RestaurantList>.value(_FakeRestaurantList_0()))
          as _i5.Future<_i2.RestaurantList>);
  @override
  _i5.Future<_i2.RestaurantDetail> restaurantDetail(String? id) =>
      (super.noSuchMethod(Invocation.method(#restaurantDetail, [id]),
              returnValue:
                  Future<_i2.RestaurantDetail>.value(_FakeRestaurantDetail_1()))
          as _i5.Future<_i2.RestaurantDetail>);
  @override
  _i5.Future<_i2.RestaurantSearch> restaurantSearch(String? query) =>
      (super.noSuchMethod(Invocation.method(#restaurantSearch, [query]),
              returnValue:
                  Future<_i2.RestaurantSearch>.value(_FakeRestaurantSearch_2()))
          as _i5.Future<_i2.RestaurantSearch>);
  @override
  _i5.Future<_i3.ResponseReview> postReview(_i3.Review? review) =>
      (super.noSuchMethod(Invocation.method(#postReview, [review]),
              returnValue:
                  Future<_i3.ResponseReview>.value(_FakeResponseReview_3()))
          as _i5.Future<_i3.ResponseReview>);
  @override
  String toString() => super.toString();
}
